[supervisord]
nodaemon=true


[program:gunicorn]
command=/app/.venv/bin/gunicorn config.wsgi:application --bind 0.0.0.0:8000 --access-logfile - --error-logfile - --log-level info  ; логи gunicorn в stdout/stderr
autostart=true
autorestart=true
user=appuser
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0


[program:celeryworker]
command=/app/.venv/bin/celery -A config.celery worker -l info -c 4 
autostart=true
autorestart=true
user=appuser
redirect_stderr=true
stdout_logfile=/dev/stdout 
stderr_logfile=/dev/stderr 
startsecs=10
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0


[program:celerybeat]
command=/app/.venv/bin/celery -A config.celery beat -l info 
autostart=true
autorestart=true
user=appuser
redirect_stderr=true
stdout_logfile=/dev/stdout 
stderr_logfile=/dev/stderr 
startsecs=10
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0